# Generated by Django 5.1.3 on 2024-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
